// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwO2XtJNatFT1bLxZi3ZgIRNStpX1_TN4',
    appId: '1:873394206828:web:afa9f46cbdd29cbfff0049',
    messagingSenderId: '873394206828',
    projectId: 'civicreporting-b8d33',
    authDomain: 'civicreporting-b8d33.firebaseapp.com',
    storageBucket: 'civicreporting-b8d33.firebasestorage.app',
    measurementId: 'G-7HNBT8ZVY5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAaHaC9Ql_1OJhE_dHLZMsJ84DAXPEhFY',
    appId: '1:873394206828:android:6029885f8b9a2facff0049',
    messagingSenderId: '873394206828',
    projectId: 'civicreporting-b8d33',
    storageBucket: 'civicreporting-b8d33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-mtHy6yCoPNfmg5zYBAy0m82HqOj_38c',
    appId: '1:873394206828:ios:508d09c926691332ff0049',
    messagingSenderId: '873394206828',
    projectId: 'civicreporting-b8d33',
    storageBucket: 'civicreporting-b8d33.firebasestorage.app',
    iosBundleId: 'com.example.civicReportApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-mtHy6yCoPNfmg5zYBAy0m82HqOj_38c',
    appId: '1:873394206828:ios:508d09c926691332ff0049',
    messagingSenderId: '873394206828',
    projectId: 'civicreporting-b8d33',
    storageBucket: 'civicreporting-b8d33.firebasestorage.app',
    iosBundleId: 'com.example.civicReportApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwO2XtJNatFT1bLxZi3ZgIRNStpX1_TN4',
    appId: '1:873394206828:web:22901eda869d0cb9ff0049',
    messagingSenderId: '873394206828',
    projectId: 'civicreporting-b8d33',
    authDomain: 'civicreporting-b8d33.firebaseapp.com',
    storageBucket: 'civicreporting-b8d33.firebasestorage.app',
    measurementId: 'G-LR2Q42253M',
  );
}
